### ISSUE TITLE
Cannot use IJobEvent<T> inside bursted ISystem

### ISSUE THREAD

**Issue by kroonhorstdino** [tertle/com.bovinelabs.event#1]
Any `IJobEvent<T>` that is scheduled inside a bursted `ISystem.Update()` will throw this error. Empty, component lookups, etc. does not matter, will throw error every time

```The managed class type `System.IntPtr` is not supported. Loading from a non-readonly static field `BovineLabs.Event.Jobs.JobEvent.JobEventProducer`2<...JobType,...EventType>.jobReflectionDataSingle` is not supported```

Error is thrown at in `BovineLabs.Event\Jobs\IJobEvent.cs` line 131

**Comment by tertle** [comment]
I already invested this a while ago and it's just not possible without a lot of manual work on your behalf as generic jobs can't get setup automatically via the il processing.
